# charts/inventory-service/values.yaml
replicaCount: 1

image:
  repository: abdelrahman404/konecta-inventory-service
  pullPolicy: IfNotPresent
  tag: "develop-11ee2d9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "inventory-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8086
  targetPort: 8085

containerPort: 8085

database:
  host: postgresql
  name: inventory-service
  username: postgres
  password: 1234

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: inventory-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgresql:5432/inventory-service"
  - name: SPRING_DATASOURCE_USERNAME
    value: "postgres"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "1234"
  - name: SPRING_PROFILES_ACTIVE
    value: "docker"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-server:8080/eureka/"

