image:
  repository: postgres
  tag: "15"

auth:
  username: postgres
  password: changeme
  databases:
    - auth-service
    - hr-service
    - finance-service
    - reporting-service
    - inventory-service

# Gateway API HTTPRoute configuration (disabled by default)
httpRoute:
  enabled: false

persistence:
  enabled: true
  size: 20Gi
  storageClass: gp3

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Ingress toggle (for templates that reference it)
ingress:
  enabled: false

# Gateway API HTTPRoute configuration (disabled by default)
