# charts/reporting-service/values.yaml
# Default values for reporting-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: konecta-reporting-service
  pullPolicy: IfNotPresent
  tag: "develop-11ee2d9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "reporting-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5160
  targetPort: 8080

containerPort: 8080

database:
  host: postgresql
  name: reporting-service
  username: postgres
  password: 1234

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: reporting-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: DOTNET_ENVIRONMENT
    value: "Development"
  - name: ConnectionStrings__DefaultConnection
    value: "Host=postgresql;Port=5432;Database=reporting-service;Username=postgres;Password=1234"


