global:
  namespace: erp-dev
  environment: minikube

gateway-service:
  service:
    type: NodePort

postgresql:
  persistence:
    storageClass: ""

frontend:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: frontend.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

mailhog:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"

inventory-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"