global:
  namespace: erp-dev
  environment: minikube

gateway-service:
  service:
    type: NodePort

postgresql:
  persistence:
    storageClass: ""

frontend:
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: frontend.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

