# charts/finance-service/values.yaml
# Default values for finance-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abdelrahman404/konecta-finance-service
  pullPolicy: IfNotPresent
  tag: "develop-29ae71d"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "finance-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8087
  targetPort: 8083

containerPort: 8083

database:
  host: postgresql
  name: finance-service
  username: postgres
  password: 1234

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: finance-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 90
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgresql:5432/finance-service"
  - name: SPRING_DATASOURCE_USERNAME
    value: "postgres"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "1234"
  - name: SPRING_PROFILES_ACTIVE
    value: "docker"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-server:8080/eureka/"
