global:
  namespace: erp-dev
  environment: dev

postgresql:
  auth:
    password: dev-password
  persistence:
    size: 10Gi
    storageClass: gp3
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

discovery-server:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

gateway-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

auth-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

hr-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

finance-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

reporting-service:
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"

frontend:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"


mailhog:
  replicaCount: 1
  image:
    repository: mailhog/mailhog
    tag: "latest"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

inventory-service:
  replicaCount: 1
  image:
    repository: konecta-inventory-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8086
    targetPort: 8085
  database:
    host: postgresql
    name: inventory-service
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"