# charts/hr-service/values.yaml
# Default values for hr-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: abdelrahman404/konecta-hr-service
  pullPolicy: IfNotPresent
  tag: "develop-11ee2d9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "hr-service"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8088
  targetPort: 8082

containerPort: 8082

database:
  host: postgresql
  name: hr-service
  username: postgres
  password: 1234

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: hr-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgresql:5432/hr-service"
  - name: SPRING_DATASOURCE_USERNAME
    value: "postgres"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "1234"
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery-server:8080/eureka/"

# Gateway API HTTPRoute configuration (disabled by default)
