apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mailhog
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - containerPort: 8025
          name: http
        - containerPort: 1025
          name: smtp
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
