apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog.fullname" . }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: smtp
      port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
  selector:
    {{- include "mailhog.selectorLabels" . | nindent 4 }}

