# charts/mailhog/values.yaml
replicaCount: 1

image:
  repository: mailhog/mailhog
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "mailhog"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  httpPort: 8025
  smtpPort: 1025

containerPorts:
  http: 8025
  smtp: 1025

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

